### ISSUE TITLE
In full screen view you do not know the exact name of the regional channel

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#10]
When e.g. switching between the NDR channels in fullscreen view I do not know whether the currently shows NDR logo is the one from Hamburg or Lower Saxony or so...

**Comment by cemrich** [comment]
You can touch the screen once to show the application bar and see which channel is currently running.

**Comment by rugk** [comment]
Mhh okay, but for fast switching between the channels, this is not solution.
There is just a small text missing under the logo or so. Or maybe you can find logos with the regional text already appended.

I suggest you to reopen this issue.
