### ISSUE TITLE
Problems on Fire TV

### ISSUE THREAD

**Issue by bjoernkoenig** [cemrich/zapp#100]
The switching of Channels on Amazon Fire TV doesn't work correct. Please optimize the app for TV Boxes.

**Comment by cemrich** [comment]
I don't own a Fire TV so I was not able to optimize very much, but I plan to do so in the future. Can you please report which version of Zapp you are using?

**Comment by cemrich** [comment]
Okay, someone has put Zapp into the Amazon store: https://www.amazon.de/jho-Zapp-Fire/dp/B06XQ84DJS/ As it wasn't me, I am unable to fix the version.

**Comment by cemrich** [comment]
I tried to submit a new version, but it got rejected (#107). So thanks to Amazon this version will remain broken and without updates.

**Comment by 1337sup3rh4x0r** [comment]
Specifically, when pressing the arrow keys on the remote control to switch channels, it skips two channels at a time. Could you look into this?

**Comment by cemrich** [comment]
Sorry, I cannot change the Amazon version in any way because the my app version got rejected and the very, very old one is sticking around.

**Comment by 1337sup3rh4x0r** [comment]
Hi cemrich, thanks for the answer!
I was referring the standard version from Fdroid, which I sideloaded to the fireTV. It works just fine, except for the mentioned channel skipping. It switches two channels at once, so I can only reach channels with even numbers this way.
