### ISSUE TITLE
Download Media Files, Small File names problems

### ISSUE THREAD

**Issue by michaelof** [cemrich/zapp#101]
Hi Christine and all who made Zapp possible,

first if all thank you very much for this nice app! I'm using MediathekView on Linux for a while, and I'm happy that with Zapp there's a similar tool for Android available.

Zapp 1.9.1 F-DROID Version
Android 6.0 Marshmallow
Lenovo C2

When Downloading media files with file names containing / you'll get not really end-user friendly  results.

E.g. when downloading this file 
 http://rodl.zdf.de/dach/3sat/15/09/150930_tannbach3_online/4/150930_tannbach3_online_2328k_p35v11.mp4, Zapp does not take the original file name, but the shown title "(3/3) TANNBACH ...". 

With this file name, Zapp creates a sub folder "(3" and below that folder a file "3) TANNBACH ...".

It might be an idea just to replace / in file names to prevent sub directories to be created.  Afaik / in file names are anyway not allowed in Android/Linux ext4 etc. file systems.

Not a big issue,
regards Michael

**Comment by cemrich** [comment]
Thank you very much for this detailed bug report! I will look into this issue for the next release.

**Comment by cemrich** [comment]
Note to myself: maybe replace with ∕ : http://www.fileformat.info/info/unicode/char/2215/index.htm

**Comment by rugk** [comment]
What replace / with /?
Just use a replacement character like `-`. Also software may behave strangely if you transfer the file to Windows or Linux or so. Or just imagine when you try to to access the file on the command line.

**Comment by cemrich** [comment]
This should be fixed with version 1.10.0. Please reopen if the problem persists.
