### ISSUE TITLE
Add a "Share with..." button to Live Stream List / channel list

### ISSUE THREAD

**Issue by chefkoch** [cemrich/zapp#102]
A button for sharing a live stream / channel  would be great, even before starting the live stream.
![screenshot_20180108-202148](https://user-images.githubusercontent.com/601866/34689256-2ac62786-f4b5-11e7-8504-d53e06f02710.png)

It is already available after stream was started.

For mediathek items it is also possible to share before starting the streams. 
![screenshot_20180108-204332](https://user-images.githubusercontent.com/601866/34689258-2c3bf65e-f4b5-11e7-8dd2-7cbe768f48e8.png)

**Comment by cemrich** [comment]
Good point, but this may take a while with my current workload.

**Comment by rugk** [comment]
As it would make the UI quite "full" when this is shown for each channel, maybe just allow the user to long-press on a channel and then there can be buttons for sharing or doing other things.

**Comment by cemrich** [comment]
I added the feature for version 1.10.0 (long press for popup menu). Please let me know if you have any further suggestions or encounter bugs!
