### ISSUE TITLE
Zapp is affected by a bug on certain Custom ROMs

### ISSUE THREAD

**Issue by STPKITT** [cemrich/zapp#103]
Hello,
using a Samsung Galaxy Grand DUOS GT-I9082 running LineageOS 13.0 6.0.1_r79 from July 2017 I discovered that Zapp is affected by the bug treated in the following links. In those links you can see that the whole problem is fixed on recent Custom ROMs. Trouble is that a lot of devices are stuck on older ROM releases so Zapp development should do the necessary steps to avoid it like the developers on the app "Conversations" did (look at the last link).

https://issuetracker.google.com/issues/64434571

https://jira.lineageos.org/browse/BUGBASH-1052

https://gitlab.com/fdroid/fdroiddata/issues/979

https://github.com/siacs/Conversations/issues/2785

Thanks and greetings!

**Comment by cemrich** [comment]
Thank you very much for your report. I will update the build tools for the next release - that should fix the issue.

**Comment by cemrich** [comment]
This should be fixed with version 1.10.0. Please reopen if the problem persists.
