### ISSUE TITLE
Publish to Amazon app store

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#107]

**Comment by cemrich** [comment]
Waiting for approval...

**Comment by cemrich** [comment]
Zapp failed approval:
- Your app facilitates piracy or illegal download of content.
- Your  app contains Multiple channel. Please provide documentation  demonstrating that you have the right to use Multiple channel in inapp.  The documentation must be either a confirmation letter from the  intellectual property rights holder or a copy of the applicable license.

So there will be no fire TV version. The target audience sideloading APKs on their Fire TV is just too small.

**Comment by rugk** [comment]
LOL, so stupid to reject this app. :roll_eyes:

**Comment by cemrich** [comment]
Well, the law is stupid to not allow this app as "fair use" or something. I'll not waste my energy on fighting Google or Amazon on this matter.
