### ISSUE TITLE
Download not starting

### ISSUE THREAD

**Issue by pmk1c** [cemrich/zapp#110]
The download feature is not working for me. When I click on a download button nothing happens.

I'm on Android 8.1.0 / LineageOS 15.1-20180409-microg-bullhead.

Let me know if / how I can give you any more (debugging) info.

**Comment by cemrich** [comment]
Thank you very much for your bug report!

Could you please let me know:
- Which shows are affected? 
- Which quality are you trying to download? 
- Do you experience an app crash? 
- Do you see a download notification after clicking the download icon?

**Comment by pmk1c** [comment]
I now tried many different shows from different channels in all qualities. I couldn't download any of them.

When clicking on the link nothing happens, meaning there is neither an exception nor a download notification. Clicking on the share button besides the download button, works without an issue.

I'm using the microG version of LineageOS, so Google services are replaced by open source microG libraries. Don't know if this could have something todo with the problem, but I doubt it.

**Comment by cemrich** [comment]
Thank you for your feedback! I will check if I can reproduce this bug on a 8.1.0 emulator.

**Comment by cemrich** [comment]
I can confirm this bug on stock android 1.1.0

**Comment by cemrich** [comment]
This issue should be fixed in Zapp 1.11.0. Please reopen if you still have trouble.
