### ISSUE TITLE
Settings - Secondary Text

### ISSUE THREAD

**Issue by ort163** [cemrich/zapp#118]
Please avoid changing the secondary text upon 'checkbox' selection. It unnecessary confuses users and looks ugly. Sorry, but if you look most 'good' apps and stock android-system-settings do not do it. [1], [2]. Not an expert coder..

Please use this https://github.com/ram-on/SkyTube
Orientation->setting. 
![1](https://user-images.githubusercontent.com/24358068/42700314-a7ab41b4-86c3-11e8-8aa0-ca01030c9384.png)

My suggestion:
https://developer.android.com/reference/android/support/v7/preference/PreferenceFragmentCompat.html

https://developer.android.com/guide/topics/ui/settings
https://material.io/design/platform-guidance/android-settings.html#label-secondary-text

**Comment by cemrich** [comment]
Hey there, thank you for your bug report! I misread the design guidelines. They explicitly encourage changing the secondary text - just not for checkbox settings.

**Comment by rugk** [comment]
But I don't understand this:

![grafik](https://user-images.githubusercontent.com/11966684/43211884-ead4eea4-9032-11e8-80f0-083b4a372067.png)

Because this actually _does not_ explain the _current status_ (which would mean it changes when toggling the setting), but is just a static text.

**Comment by ort163** [comment]
@rugk It is a 'switch' not a checkbox. I do agree, however, things are not clear. I leave my judgement on some of the well known apps/system settings.

**Comment by cemrich** [comment]
It works quite nicely without changing the text, so the change will be part of the next release.
