### ISSUE TITLE
Settings - W-Lan

### ISSUE THREAD

**Issue by ort163** [cemrich/zapp#119]
Please rename:
Nur über W-Lan streamen
to
Streaming in Mobilfunknetz
(reverse the 'logic' in Preferences->  checkbox).

In the secondary text you can add. Videos spielen unabhängig von der Verbindungsart ab und können dein Mobilfunk-Volumen belasten. 
The text does not have to change based on tick mark. 

BTW it is always WLAN. Thanks for your great work. Sorry to find mistakes!

**Comment by rugk** [comment]
> Sorry to find mistakes!

That's the purpose of this issue tracker, i guess. :smile:

**Comment by cemrich** [comment]
Thank you for your report!

I fixed the typo but will not reverse the setting for two practical reasons:
1. I would have to migrate the old, negated setting value which clutters the codebase.
1. The network check explicitly asks for a WIFI connection and only then allows streaming. So the wording -as it is now- is correct.
