### ISSUE TITLE
ARD stream does not work anymore

### ISSUE THREAD

**Issue by jw243** [cemrich/zapp#120]
Hi,
for a few days now, the ARD stream does not work anymore. An update to correct this would be greatly appreciated.
Best regards.

**Comment by cemrich** [comment]
Thank you very much for this report! I'll fix the url and release a new version as soon as possible.

**Comment by cemrich** [comment]
This issue is fixed with the 1.11.1 release. It will take a while until it hits the F-Droid repository.
