### ISSUE TITLE
Tatort not available in Zapp while it's on air -- but it is in Mediathek

### ISSUE THREAD

**Issue by dadosch** [cemrich/zapp#122]
Während der Tatort noch im Fernsehen läuft, ist er nicht in Zapp verfügbar, obwohl er online in einer (vermutlich) von der (Hauptmediathek der) ARD getrennten Mediathek ist.

Gleiches gilt z.B. auch für Vorschauen, wie https://www.daserste.de/unterhaltung/krimi/tatort/sendung/im-gelobten-land-104.html

--
P.S: Vielen Dank für diese spitzenmäßige App :smiley:

**Comment by cemrich** [comment]
Vielen Dank für den Bug-Report!

Zapp greift auf die API von [MediathekViewWeb ](https://mediathekviewweb.de/) zu, auf die ich leider keinen Einfluss habe. Falls die Sendung auch dort in der Websuche nicht auftraucht, wäre ein Bug-Report am besten im Mediathek-Crawler (https://github.com/mediathekview/MServer/issues) oder im Forum (https://forum.mediathekview.de/) aufgehoben.

**Comment by dadosch** [comment]
Könnte es sein, dass der (noch laufende) Tatort dort als "zukünftig" markiert ist? Und weil hier https://github.com/cemrich/zapp/blob/362fde1e8b090555ddd4a806f07f15ec13a13169/app/src/main/java/de/christinecoenen/code/zapp/app/mediathek/api/request/QueryRequest.java#L19 `future = false` gesetzt wird, er dann auch nicht in Zapp auftaucht?
Der Tatort (keine Neuaustrahlung, Sendetermin 15.10.) "Der rote Schatten" etwa taucht nur in MediathekViewWeb auf, wenn man "zukünftig" aktiviert (in Zapp taucht er nicht auf)

**Comment by klawdhfzasjhaa** [comment]
Same issue is discussed here: #177
