### ISSUE TITLE
MarkdownView doesn't seem to be available anymore?

### ISSUE THREAD

**Issue by dadosch** [cemrich/zapp#127]
I just tried to build Zapp using AndroidStudio (want to add a setting for "future" setting as in https://github.com/cemrich/zapp/issues/122#issuecomment-422891434), and it fails when Gradle syncing with a 403 on `https://jitpack.io/com/github/fiskurgit/MarkdownView/1.1.0/MarkdownView-1.1.0-sources.jar`

If I open this link in a web browser, it shows `Subscription not active`. I suppose that the original repo at github.com/fiskurgit/MarkdownView has been deleted?

If this is just a Android Studio setup error, I apologize for interrupting :smiley:

**Comment by cemrich** [comment]
This is weird - it does build just fine on my machine... I'll try to reproduce the issue.

**Comment by cemrich** [comment]
I did everything to reproduce the issue without success. Deleting the gradle cache and forcing a re download did not help. But I suspect the lib may still be cached somewhere on my machine. 

Does anyone experience the same issue?

**Comment by cemrich** [comment]
I replaced the library. Can you please confirm that building does now work for you?

**Comment by dadosch** [comment]
Jep, Builds successfully now

**Comment by cemrich** [comment]
Nice, thank you!
