### ISSUE TITLE
Paused video automatically starts playing when WIFI is being connected

### ISSUE THREAD

**Issue by aeph6Ee0** [cemrich/zapp#128]
# Description
When a video from the Mediathek is paused and a WIFI connects, the video starts playing.
This even happens when the app is in the background and the phone is locked.

# Example
An example will illustrate the severity of the problem:

I was watching a video in the app at home over WIFI. Then paused the video and went to work. On the way I had no internet.
In the middle of a meeting, the phone connected to the work WIFI. The paused video automatically started playing in the background at full volume! I had to search for my phone, enter my pin code to unlock it, search for the app and press the pause button to make it stop.
That was quite an uncomfortable situation.

Thank god, there is no pr0n is the Mediathek. The effect would be devastating!

# How to reproduce
- Play random video from the Mediathek
- Pause the video
- Disconnect WIFI
- Connect WIFI
- Effect: Video starts playing without any user interaction

# System Information
- OS: LineageOS 14.1-20181005-jfltexx (Android 7.1.2)
- App: Zapp 1.11.1 (via F-Droid)

**Comment by cemrich** [comment]
Thank you very much for your detailed bug report!
I had the same issue at night during sleep, but was not able to reproduce it. There will be a major rewrite of the player functionality which will hopefully fix this issue.
