### ISSUE TITLE
Does not find all content

### ISSUE THREAD

**Issue by htgoebel** [cemrich/zapp#131]
I was recommended the video [Max Schrems und sein Einsatz für den Datenschutz](https://www.br.de/mediathek/video/av:5bd48b5d747e4100184a9c92), dates 2018-10-26, which as of today is available at the BR mediathek. 

When searching for "schrems" in zapp, I did not get any result. Whereas [mediathekview](https://mediathekview.de/) lists this video when searching for "Schre", see screenshot.
![bild](https://user-images.githubusercontent.com/784161/48472654-01ec4580-e7f7-11e8-9101-3f915caca7b8.png)

I would expect the entry to be listed in zapp, too.

**Comment by cemrich** [comment]
The entry does show up in the current version of zapp. Maybe https://mediathekviewweb.de/ took some time to update its database? Please reopen this issue if your problem persists.

**Comment by htgoebel** [comment]
https://mediathekviewweb.de/ does not show this entry when searching of "schrems" as of now. 
![screenshot_20181115_153241](https://user-images.githubusercontent.com/784161/48559642-486f9c00-e8ec-11e8-90d0-9541a8285b80.png)
Same does zapp 2.0.0 from F-droid.
![screenshot_20181115-153011_zapp](https://user-images.githubusercontent.com/784161/48559829-b1571400-e8ec-11e8-9454-57e91058c6ee.png)

What is the search term you are using?

**Comment by cemrich** [comment]
Okay, this is really weird. I'm getting following results:

![grafik](https://user-images.githubusercontent.com/403202/48565620-452edd00-e8f9-11e8-9222-fa643f19d904.png)

![screenshot_20181115-171540](https://user-images.githubusercontent.com/403202/48566227-97243280-e8fa-11e8-945c-892a10949950.png)

**Comment by cemrich** [comment]
And now its gone in both apps o.Ô
Looks like an issue with https://github.com/mediathekview/mediathekviewweb or the mediathekview crawler. I am sorry, but I can't fix this in Zapp :(

**Comment by htgoebel** [comment]
@cemrich If the external data source is not reliable, you can not change anything anyway. But thanks a lot for taking a care and taking this serious.

**Comment by return42** [comment]
> And now its gone in both apps o.Ô

Same *here*  .. I guess they updated their database in between. Anyway, this entry seems broken me.
