### ISSUE TITLE
Sometimes downloads are just downloading a playlist file instead the video file that is referenced in it

### ISSUE THREAD

**Issue by alexanderadam** [cemrich/zapp#133]
See title :wink: 

Thank you so much for Zapp :+1:

**Comment by bagbag** [comment]
For example ORF doesn't offer mp4s for most of their videos anymore, only m3u8 files for streaming. For the same reason it isnt possible at MediathekViewWeb anymore.

MediathekView (the Java client) solves it by feeding it into ffmpeg, which concatenates all the streaming chunks and spits out a single mp4.

**Comment by cemrich** [comment]
Thanks for the info @bagbag . I would like to avoid duplicating code in backend and frontend. Most likely I will disable download entirely for playlist files.

**Comment by bagbag** [comment]
It's not in the backend, but at client-side. MediathekViewWeb API returns more or less just raw filmlist data.

**Comment by cemrich** [comment]
Yes, sorry, I wasn't clear. I think the API should return the .mp4 links. Ideally the mediathekview scraper should return them whenever possible. I will leave this ticket open and sleep about it.

**Comment by bagbag** [comment]
You're right, it would be the best, if it the crawlers emit that. I also told them, but for reasons I don't know, they don't do that.

Actually, you're right. I'll migrate that code to the server.

**Comment by cemrich** [comment]
> Actually, you're right. I'll migrate that code to the server.

Thank you very much! However, I'll guard against m3u downloads just to be save.

**Comment by bagbag** [comment]
It's live, so WDR and BR should also work for Zapp now.
