### ISSUE TITLE
TLS 1.3

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#135]
https://github.com/cemrich/zapp/blob/52222dc3cc13d8d4106034f65fbdf8a1a145a7a9/app/src/main/java/de/christinecoenen/code/zapp/app/mediathek/ui/list/MediathekListFragment.java#L94

BTW, what about TLS 1.3 support. Browsers already have it, many web servers, too. It may likely come to the servers streaming these videos, soon, too…

**Comment by cemrich** [comment]
I can add TlsVersion.TLS_1_3 but I have no idea what the implications are or if existing functionality will break. I am happy about any advice.

**Comment by rugk** [comment]
AFAIK it should fallback… :smile: I hope… :innocent:
