### ISSUE TITLE
Abweichende Signatur zur installierten Version

### ISSUE THREAD

**Issue by wrohdewald** [cemrich/zapp#139]
I am getting this for all versions up to 2.1.0 (2.1.1 not yet being in F-Droid) on a Samsung Galaxy Tab S4 with Android 8.1.0

Zapp  has never been installed on this tab before.

**Comment by cemrich** [comment]
This error happens when you have installed a Github version of Zapp and then try to update it from F-Droid. You should make sure Zapp is not installed on your device (go to Settings > Apps). If you have multiple users configured on your device, please make sure Zapp has not been installed by another user!

**Comment by wrohdewald** [comment]
Well - as I said Zapp has never been installed on this Tablet, neither from F-Droid nor from Github. The only thing in that direction is ZDFmediathek. No multiple users.

But now I tried again. Two difference to yesterday:
- 2.1.1 is now being offered in the list of versions
- for all versions including 2.1.1 I get a button "DOWNGRADE"

I also noticed that when searching for Zapp in F-Droid, the list results says Zapp Version 2.2.49
Now where does 2.2.49 come from?

I am still waiting with trying DOWNGRADE to 2.1.1, maybe you want me to check something first.

**Comment by wrohdewald** [comment]
Package Viewer 2.0 does not find any package id starting with ".de" . I only got this tablet a few days ago.

Should I report this to the f-droid developers?

**Comment by cemrich** [comment]
This is really odd behavior... This is most likely a F-Droid issue. F-Droid builds every app from source and signs it with its own keystore, so there should be no signature mismatch.

You could try reinstalling F-Droid or downloading and installing the [latest Zapp apk](https://f-droid.org/packages/de.christinecoenen.code.zapp/) from your browser. If installing manually works and F-Droid continues to throw errors, I would suggest to open a new bug report on the [F-Droid tracker ](https://gitlab.com/fdroid/fdroidclient/issues), linking to this issue.

**Comment by wrohdewald** [comment]
after manually installing the apk, F-Droid behaves correctly.
