### ISSUE TITLE
Swap volume and brightness swipers

### ISSUE THREAD

**Issue by Nuntius0** [cemrich/zapp#140]
Please consider swapping the [volume](https://github.com/cemrich/zapp/blob/3aeb6e08cf622449236d5c257bbf503403e9648b/app/src/main/java/de/christinecoenen/code/zapp/utils/video/SwipeablePlayerView.java#L89) & [brightness](https://github.com/cemrich/zapp/blob/3aeb6e08cf622449236d5c257bbf503403e9648b/app/src/main/java/de/christinecoenen/code/zapp/utils/video/SwipeablePlayerView.java#L93) control quick gestures such that **volume** is on the **right** and **brightness** is on the **left**.

Why? Both VLC and NewPipe have it this way around, which makes it confusing.

**Comment by cemrich** [comment]
Thank you very much for your feedback! 

You make an excellent point I missed while developing this feature. I will look into it for the next release of Zapp.

**Comment by bagbag** [comment]
VLC and NewPipe is not alone, also [MX Player](https://play.google.com/store/apps/details?id=com.mxtech.videoplayer.ad) (probably the most downloaded player on android out there), has it that way.

**Comment by cemrich** [comment]
This issue will be fixed in version 2.2.0, which will hit F-Droid in a view days. Please reopen if you still experience any issues.

**Comment by Spielmops** [comment]
I found the gestures, they are very close to the edges ...

Spielmops
