### ISSUE TITLE
Zoom-to-fill pinch gesture

### ISSUE THREAD

**Issue by gepolemi** [cemrich/zapp#141]
Let users expand the video to full-screen on devices with 18:9 aspect ratios with a pinch gesture like the YouTube app has.

**Comment by cemrich** [comment]
Sadly, I cannot support this right now as I have no test device.

**Comment by bagbag** [comment]
What's about the Android Emulator?
Might be a slow development, but I could test it for you, if you want.

**Comment by cemrich** [comment]
Such a feature does not only require testing during implementation but for every release build as it might break during development. Right now I cannot support this, because I think other core features and updates are more important. Especially given that Zapp is a one women project at the moment.

**Comment by cimbrico** [comment]
The folks from @TeamNewPipe had the same issue fixed a while ago.
Maybe their pulls will help as they use ExoPlayer, too:

https://github.com/TeamNewPipe/NewPipe/pull/1067
https://github.com/TeamNewPipe/NewPipe/pull/1748
https://github.com/TeamNewPipe/NewPipe/pull/1770

I'd be willing to do testing on my 18:9 device.

**Comment by cemrich** [comment]
Thank you for the hint @cimbrico Hopefully I'll get my new phone soon and can continue development.

**Comment by cemrich** [comment]
This issue will be fixed in version 2.2.0, which will hit F-Droid in a view days. Please reopen if you still experience any issues.

**Comment by fischschuppe** [comment]
Works great for me!
How about adding a toggle for this to the settings menu?

**Comment by cemrich** [comment]
@ghost I disabled pich-to-zoom when the aspect ratio of the video matches the one of the screen. In this case, is a setting really needed? Does the pinch gesture confuse users? 
I would like to keep the settings menu as small as possible.

**Comment by thionthi** [comment]
I think your reasoning makes perfect sense @cemrich. An additional option would be redundant.
