### ISSUE TITLE
Chromecast support?

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#15]
Might be an idea for a feature.

E.g. the Fennec (Firefox for Android) implements this.

**Comment by cemrich** [comment]
I thought about that. Is there a fDroid compatible, up to date open source solution for chromecast support?

**Comment by rugk** [comment]
Maybe have a look at https://bugzilla.mozilla.org/show_bug.cgi?id=901803. It seems Google provides an SDK.

**Comment by frankmorgner** [comment]
example code is here https://github.com/googlecast/CastVideos-android

**Comment by cemrich** [comment]
Thank you! 

I've checked with fDroid developers: The official SDK is not allowed inside fDroid and there are no Open Source alternatives at the moment. So this feature has to wait until Zapp is released to the Play Store. Then we can use Gradle to build different flavors for fDroid (without chromecast) and Play Store (with chromecast).

**Comment by rugk** [comment]
At least I see that NewPipe (a YouTube app, also on FDroid) has Chromecast support (at least the icon is there sometimes) - you may look at how they do it.

**Comment by cemrich** [comment]
They support streaming to Kodi but not Chromecast, because they have the same problem. See TeamNewPipe/NewPipe#351

**Comment by cemrich** [comment]
Google rejected the app (as will - most likely - amazon), so I'll have to use another store for this feature.

**Comment by monofone** [comment]
What are the reasons provided by google to reject the app from the playstore ?

**Comment by cemrich** [comment]
See #39 - I pasted the rejection mail over there. The essence is "it violates the unauthorized use of copyrighted content policy".

**Comment by cemrich** [comment]
Under this circumstances chromecast support is not going to happen in the near future.
