### ISSUE TITLE
ARD livestream broken

### ISSUE THREAD

**Issue by seebronn** [cemrich/zapp#150]
the ARD livestream doesn't work since some days. I found the new adress:
https://mcdn.daserste.de/daserste/de/master.m3u8

Please insert into zapp.
The zapp app is great. I use it via sideload on Amanzon fire stick. The best livestream app.

**Comment by cemrich** [comment]
This issue will be fixed with version 2.2.1 which will hit FDroid in a few days. Thank you very mich for reporting!

**Comment by Ricolette256** [comment]
That's strange! I have just deinstalled old ZAPP release and then installed new ZAPP from F-Droid. The problem still is the same. A some weeks old part of "Tagesschau" is playing around and round instead of seeing live program.
Perhaps it is better, to check this again?

**Comment by cemrich** [comment]
@Ricolette256 I cannot reproduce this issue. Can you please check, which version of Zapp is installed on your device? 2.2.2 is the latest version right now.
