### ISSUE TITLE
App stürzt nach Sortierung der Sender ab

### ISSUE THREAD

**Issue by deejay73** [cemrich/zapp#152]
In den Versionen 2.2.0 und 2.2.1 stürzt die App ab, wenn man die Sender neu sortiert.
Vor der Sortierung scheinen die Versionen zu funktionieren, bis man auch nur einen Sender verschiebt. Dann Absturz! Ein Neustart der App ist dann nicht mehr möglich, nur Neuinstallation  bringt Abhilfe. In der Version 2.1.1 ist dieser Fehler noch nicht enthalten. Getestet mit Honor 10 View, Android 9.0 sowie Samsung Galaxy S4 mit Android 8.1.

**Comment by cemrich** [comment]
I can reproduce this issue. Thank you for reporting!

**Comment by cemrich** [comment]
Ach, was liebe ich Fehler, die nur im Release auftreten....

**Comment by cemrich** [comment]
Der Fehler sollte in Version 2.2.2 behoben sein (wenn nicht, bitte dieses Issue wieder öffnen). Erfahrungsgemäß dauert es ein Paar Tage, bis die Version auf F-Droid auftaucht.
