### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#153]
As releases tend to break silently with Gradle and build tools upgrades, I have to consider some continuous integration solution for Zapp.

https://www.browserstack.com/ has a free Open Source plan and looks promising. Suggestions are welcomed!

**Comment by userdimi** [comment]
In my opinion travis ci is a good solution for open source project. Please have a look at it
https://travis-ci.org

**Comment by cemrich** [comment]
@userdimi Thank you for this hint. I'll check it out.

**Comment by bagbag** [comment]
An alternative would be GitLab CI (can also be integrated for a repository at GitHub). I'm using that myself for MVW: [https://gitlab.com/patrickhein/mediathekviewweb/pipelines](https://gitlab.com/patrickhein/mediathekviewweb/pipelines).

**Comment by cemrich** [comment]
@bagbag Thank you for this hint. I'll look into it. But I've set up Travis CI for the moment - it does integrate quite nicely with github.
