### ISSUE TITLE
Show stream and live information at the same time

### ISSUE THREAD

**Issue by SebiderSushi** [cemrich/zapp#154]
It would be very nice to be able to watch a stream while browsing through the "Live" tab to see what's being bradcast on other channels without needing to leave the current stream.

A possible implementation could be:
If in portrait mode, show a split screen with the video in the upper area of the screen and the "Live" tab in the remaining bottom area of the screen.
Preferrably add a Button to manually switch between portrait and landscape mode to facilitate switching for users like me, who almost never enable automatic screen rotation.

**Comment by cemrich** [comment]
Thank you for your suggestion! Would a picture-in-picture (https://developer.android.com/guide/topics/ui/picture-in-picture) mode like YouTube match your use case? 
This feature is available since Android Oreo and would be a nice addition for Zapp. However, implementing it would take quite some time.

**Comment by SebiderSushi** [comment]
Since a picture-in-picture mode would always obfuscate a part of the UI the user would have to drag it around all the time to keep looking at all the live information in my use case. A picture-in-picture mode would be super nice in itself but I was thinking of a UI change so that whenever a live stream is played, the channel list on the main activity will shrink to take up only the bottom 2/3 of the space and the contents of the player activity will be initialized in the remaing upper third of the UI space.
&nbsp;In this implemetation there should be two new buttons: A stop button that stops video playback and causes the player to vanish and the channel list to expand to full size again and a button to switch between fullscreen and split screen on the fly even if automatic rotation is disabled.

&nbsp;There could maybe even be a distinct tablet UI for landscape mode where the screen is split horizontally.

&nbsp;Concerning PiP mode: Maybe Zapp could offer to open video URLs in VLC if it is installed. That way PiP could be used even independently from Android Oreo. As this obviously lacks swipe supprt for zapping it might be more attractive for streaming content from the media centers so a seperated switch should be a consideration in this case so the user can e.g. keep playing live streams in Zapp itself.

**Comment by cemrich** [comment]
@SebiderSushi Thank you for your detailed feedback!

You can share mediathek shows and live streams with VLC and other video players right now. 

Regarding your feature request: I think your usage scenario is quite special and complicated to implement. Picture in picture mode would help you with your goal of seeing broadcast information while playing back a single channel. At the same time a lot of other users can benefit from this feature and it does meet the Android design guidelines.

I opened #155 instead and will close this issue.

**Comment by SebiderSushi** [comment]
Thank you very much for your answer, although it is sad to hear. But all in all it is quite obvious that with your app you are trying to keep it simple. Perhaps if more people came up showing interest in this particular feature, would you reconsider your stance on implementing it as it's usage scenario wouldn't be so special anymore?

Besides that, thank you for the hint. I never bothered giving a share button a shot for opening something in another app since that action is labeled "open in..." in my brain. By sharing i would merely expect telling my friends what i was watching, via Messengers, E-Mail or the like. That would, in my expectation, not even include the link to the streamed file rather than the link to the shows info page on it's broadcasting stations homepage as something with informatiom to show someone else.
Maybe changing the title of the action might be a good step here since that would make it consistent to the use of the terms "Share" and "Open in" among the whole Android ecosystem, especially since opening the stream in other players really is the only option given here.
