### ISSUE TITLE
HD streams?

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#16]
Are there no HD streams available?

**Comment by rugk** [comment]
I found out that at least [tagesschau24 offers](https://wiki.ubuntuusers.de/Internet-TV/Stationen/#tagesschau24) different streams and there is also a HD stream available.

**Comment by cemrich** [comment]
Almost all channels offer their HD streams in f4m format (some Adobe manifest file) which cannot be played by any player not based on Adobe Flash. At the moment it's too much overhead to implement an UI just for this one channel.

**Comment by cemrich** [comment]
I'll investigate further in #7
