### ISSUE TITLE
volume pretty low

### ISSUE THREAD

**Issue by Wiredframe** [cemrich/zapp#161]
Compared to my other apps the volume seems to be pretty low in Zapp. Is there a chance that this could be fixed? Thanks! Really enjoy using this app. 👍

**Comment by cemrich** [comment]
Can anybody confirm this issue?

@Wiredframe What device are you using an which Android version?

**Comment by userdimi** [comment]
@cemrich I can't reproduce the issue. The volume is pretty good especially if you bumped up the volume by sliding up on the right side of the screen

**Comment by Wiredframe** [comment]
I'm using a Galaxy S10e. I compared the volume of Spotify, Music Player and Zapp. Zapp had a lower volume compared to the others I think. But I could be wrong too. ^^

**Comment by cemrich** [comment]
@Wiredframe @userdimi Thanks for the feedback!

**Comment by cemrich** [comment]
I'll close this for now. Feel free to reopen if anybody is able to reproduce this issue.
