### ISSUE TITLE
Support Kitkat devices

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#18]
It would be preferable to support devices with api level 19 (4.4) and higher. I will not support lower api levels, because the gain of users is not worth the struggle. The app does run on 4.4 devices, but there are minor issues and lint warnings:
- [x] 'android:windowDrawsSystemBarBackgrounds' requires API level 21 (current min is 19)
- [x] 'android:statusBarColor' requires API level 21 (current min is 19)
- [x] some of the vector images are not fully supported (will be replaced anyway)
- [x] CollapsingToolbarLayout does not collapse
- [ ] progressbars are styled in holo theme
- [x] some runtime logcat warnings from v7 support library

I have no actual device to test those issues, so help is appreciated.

**Comment by rugk** [comment]
I successfully use this so app b Android 6.0.1, so this is certainly a higher api level.

**Comment by cemrich** [comment]
This one is resolved thanks to @rnauber and pull request #47
