### ISSUE TITLE
Adjust time difference of programs

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#23]
Sometimes the life stream is so much delayed that it does not match the time shown in the program info. This means that e.g. at the start of a TV program the progress bar is already at 20% or so.

**Comment by cemrich** [comment]
Is this the case for all channels or just specific ones?

**Comment by rugk** [comment]
I assume it us an issue of all channels, but I noticed it with zdf when creating this issue.

**Comment by rugk** [comment]
Ha, maybe it also just was https://github.com/cemrich/zapp/issues/27. 😆 
We should have a look on it...

**Comment by cemrich** [comment]
Did this issue reoccur after the update?
