### ISSUE TITLE
Playback not working on Cyanogenmod 12.1

### ISSUE THREAD

**Issue by Gyges88** [cemrich/zapp#24]
Playback of any channel fails to start saying "Video kann nicht wiedergegeben werden".
I'm using a Honor Holly (Hol-U19) with Cyanogenmod 12.1, without Gapps.

**Comment by cemrich** [comment]
Thank you for your bug report. 

Which version of the app are you using? Can you provide the logcat messages (ChannelDetailActivity should log error details)?

**Comment by rugk** [comment]
Again make sure that this is not caused, because of geoblocking (https://github.com/cemrich/zapp/issues/28). However when you say it affects each channel, this usually does not apply.

**Comment by Gyges88** [comment]
I'm located at Germany, so no geoblocking issue, I guess.
I used v1.0.0 and 1.0.1 having this error message. I also tried v1.1.0. After hearing a sound for a fraction of a second the playback stops saying "Es gab einen Fehler beim Abspielen. Vielleicht besteht keine Internetverbindung."
The logs don't seem to be useful, ChannelDetailActivity report no errors:

2016-10-06 05:07:07,INFORMATION,ActivityManager,Android-System,Displayed de.christinecoenen.code.zapp/.ChannelDetailActivity: +335ms
2016-10-06 05:07:07,INFORMATION,Timeline,Android-System,Timeline: Activity_windows_visible id: ActivityRecord{1ba3c435 u0 de.christinecoenen.code.zapp/.ChannelDetailActivity t2136} time:8201259
2016-10-06 05:07:08,DEBUG,ChannelDetailActivity,Zapp,play: Das Erste

However, once I got this Message:
2016-10-06 05:00:27,DEBUG,Cache,Zapp,cache miss: ZDF, show too old

Hope this helps!

**Comment by cemrich** [comment]
The error indicates that your [Android Media Server died](https://developer.android.com/reference/android/media/MediaPlayer.html#MEDIA_ERROR_SERVER_DIED). The documentation on this error is not very helpful. My guess is that your internet connection might be a bit wonky or your phone can't handle the codec. You can share a stream if you press the menu button and click "Teilen". If other video apps can't play the stream either, this is no app bug but something related to your phone.

The "cache miss" message is unrelated to video playback.

**Comment by cemrich** [comment]
Thank you for investigating this. 
Yes, this errors suggest a codec problem. It's a shame the android error messages are this imprecise...

In future releases I'll add a toubleshooting section (#36) so users can investigate why they have these problems.
