### ISSUE TITLE
Communicate geoblocking to users outside of Germany

### ISSUE THREAD

**Issue by cakletzing** [cemrich/zapp#28]
On Samsung S7 (930V), only a few streams work. For example, ARD does, but ZDF and 3Sat do not.
The error message is "Can't play this video."

**Comment by rugk** [comment]
I assume this is a network error rather than an error with the app.
AFAIK at least ZDF uses Geoblocking for the live stream, so you need a German IP. In my tests I saw that ARD e.g. does *not* use Geoblocking here.

**Comment by cakletzing** [comment]
Thanks for the quick response. That makes sense. It might be good to add a
note about this to the app description so that people know what is
happening.

**Comment by cemrich** [comment]
Thank you very much for your report!

Version 1.1.0 will be released soon on fDroid and provide more precise error messages. I'll add a warning about geoblocking to the app description and to the app itself in the next release.

**Comment by cemrich** [comment]
All right, the error messages, readme and fDroid description have been or will be updated. In future it would be nice to know which countries are geoblocked, but that's not as easy because it may be different for every show. So this is the quick and easy solution for now.

**Comment by rugk** [comment]
> In future it would be nice to know which countries are geoblocked, but that's not as easy because it may be different for every show.

Really? I would have thought ZDF e.g. blocks all non-German users.
But you seem to be right [this is a little more difficult](http://www.daserste.de/service/kontakt-und-service/das-erste-mediathek/index.html)... :expressionless:
