### ISSUE TITLE
Change share button

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#29]
Currently the share button shares the URL of the livestream. However for sharing this to friends this is very inconvenient as one has to have an so to open it and when one ink l opens it in the browser it will not work properly.

That means that the share button is actually more useful for playing the live stream in another app.

That is why I propose the following:
1. Rename share button to "open/play in another app" or similar
2. Add a new share button, which shares a text. This text should include some metadata about the current program (what is running, which channel, ...), so that the receiver can see this in the "traditional" TV, and IMHO a link to your app. (Yes I think you should advertise your app there, e.g. like "you can see this right now with Zapp https://fdroid.org/...".

It would of course be awesome if you could not only include a link to your app, but also a custom URL/URI, which opens Zapp with the share life stream.
Preferably this would be the same link, so you just include the channel name in the url. When accessed via the browser you can ignore this, when accessed with the app you use this into to select the channel.
Note that in this case you should really use your own domain as I do not want all my FDroid links being opened with Zapp, e.g.

**Comment by cemrich** [comment]
I don't think this feature is worth the amount of work right now. To be valuable the shared information has to contain the name of the current show and right now the program info API is not stable enough to provide this in every case. Also, a link to the website of the running show would be nice. This can be done in the far future but will be too much overload now.

**Comment by rugk** [comment]
So why not leave this issue open? Maybe use a "far future" milestone or something similar.
