### ISSUE TITLE
Allow portrait mode

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#30]
As a setting you should allow the portrait mode. I think at least for tablets this can be useful in some situations and you should not force the user to view a stream in a particular way.

**Comment by rugk** [comment]
Hmm, maybe an option for this would be better. I assume some users like the way it works currently. (as it prevents accidental rotations). However, of course, these users could just disable the rotation system-wide.

**Comment by cemrich** [comment]
This was the quickest solution. I'll add a preference when enough preferences come together.
