### ISSUE TITLE
Multiwindow support

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#31]
Android 7 (so nougat, or CM 13 where this was backported) has multi window support.

It would be nice if your ago would be compatible to this, because then one can look a life stream and do something different at one time.

**Comment by cemrich** [comment]
Yes, this is a feature I had planned. Didn't know CM 13 had multiwindow support - that's nice to test 👍

**Comment by rugk** [comment]
Yes, you just have to enable it in the settings.

**Comment by cemrich** [comment]
It's enabled by default. Just did some lifecycle handling.
