### ISSUE TITLE
Bundestag-Channels not working after update to 1.2.0. (MIT)

### ISSUE THREAD

**Issue by mgw** [cemrich/zapp#40]
with Android 6.0.1 (Galaxy A5)
"Der Stream konnte nicht geladen werden..."

**Comment by cemrich** [comment]
Thank you for your report. The bug is fixed in version 1.2.1 which should be available in fDroid in about two days (their build servers are a bit slow).

Bundestagsfernsehen broke their SSL certificates so the stream does not load on Android. Switching to http resolved the issue.

**Comment by rugk** [comment]
Oh, now no HTTPS there too. :cry:
