### ISSUE TITLE
GTK application or Kodi Addon?

### ISSUE THREAD

**Issue by BengaloBongali** [cemrich/zapp#42]
I love this app! Thank you very much! Is there something similar for Linux or could a Linux application or a Kodi Addon be created from your project?

**Comment by rugk** [comment]
Preferably something, which is ditstro-independent. :smiley: 

BTW: In general you can of course just use VLC and copy/paste the [stream URLs](https://github.com/cemrich/zapp/blob/master/app/src/main/res/raw/channels.json) there.

**Comment by cemrich** [comment]
I don't plan on porting the app, but feel free to grab the source code. With the json of stream URLs and the channel logos you could get very far.

**Comment by BengaloBongali** [comment]
Would it be possible to provide a m3u-playlist that can be used with the "PVR IPTV Simple Client" for Kodi? Maybe even EPG/XMLTV and channel logos? That would totally do it!

**Comment by cemrich** [comment]
I don't have the time right now to start another project and I've never used this plugin. However, there is a very straightforward [description](http://kodi.wiki/view/Add-on:IPTV_Simple_Client) on how construct the playlist and provide the logos. Feel free to copy over the stream urls from Zapps json and use the logos.

**Comment by vanMacG** [comment]
I managed to create an playlist and got the list in Kodi. What's missing is the EPG-info. In your app Zapp one sees the actual show/movie/etc. Where/How do you get this information so I can try to grab it and create an epg xml?

**Comment by cemrich** [comment]
For program info I scrape the channels websites and extract the relevant information. It is a separate project for the back end: https://github.com/cemrich/zapp-backend 

You make get requests to `https://zappbackend.herokuapp.com/v1/shows/<channel_name>` to get the current program info for the given channel in json format. A list of channel names can be found at https://github.com/cemrich/zapp/blob/master/app/src/main/java/de/christinecoenen/code/zapp/app/livestream/api/model/Channel.java

Feel free to fork the backend and tweak it for your needs or to query the api endpoint above. However, I can not guarantee the api is always available or the response format or endpoints will not change at some point.

**Comment by jspricke** [comment]
If someone is looking for a desktop application:
I've added TV support to my console app based on the Zapp data:
https://jochen.sprickerhof.de/Software/Radio/
Thanks for providing it!

**Comment by d-k-bo** [comment]
FYI, I am working on a GTK application that aims to offer a similar experience to zapp. See https://github.com/d-k-bo/televido or https://flathub.org/apps/de.k_bo.Televido.

**Comment by tristan-k** [comment]
Is there a m3u playlist with all zapp channels available whichs works with TVHeadend?

**Comment by jspricke** [comment]
@tristan-k here is a small Python script to generate a m3u:
```Python
import urllib
import json

print("#EXTM3U")
channels = json.load(urllib.request.urlopen("https://raw.githubusercontent.com/mediathekview/zapp/main/app/src/main/res/raw/channels.json"))
for channel in channels:
    print(f"#EXTINF:-1,{channel['name']}")
    print(channel["stream_url"])
```
