### ISSUE TITLE
Order channels directly in main screen

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#43]
Continuing https://github.com/cemrich/zapp/issues/6: I think the ordering (UX) can be improved. A submenu is not so easy to use for the user.

It would be much better if they can just be drag & dropped directly from the main screen. A UX similar to the one known from home screens/launchers would be preferable, which means:
* one tap just launches/opens the channel/app
* holding and tapping (longer) gives some feedback (habtic feedback aka vibration and/or visual feedback) and then lets the user move the item

**Comment by cemrich** [comment]
I don't think the user needs to adjust the channel order very often and the way it's implemented the user is able to find it without any usage guide or explanation. Also #9 is still open and has to work with the existing ui. This would be difficult to implement into the main screen.

**Comment by rugk** [comment]
> I don't think the user needs to adjust the channel order very often and the way it's implemented the user is able to find it without any usage guide or explanation. 

Yeah, it's not bad, but it's also not very intuitive. Also the apps on the home screen are not reordered very frequently, but the implementation of reordering them is still not hidden in a submenu.

Also of course this issue is not that important, so I am fine if you'll want to work on #9 before.

**Comment by cemrich** [comment]
As long press is now reserved for the new popup menu and this feature has a very low priority, I'll close for now.
