### ISSUE TITLE
SRFinfo and ORFE

### ISSUE THREAD

**Issue by Amadeus17** [cemrich/zapp#44]
It's no issue, is a wish.

First of all: many Thanks for your great App!

It's possible to integrate the swiss television channel SRF info and the Austrian television channe ORFE?

Both channels are almost free over satellite. Sometimes the channels are encrypted. The background: Its possibility to see the swiss TV-news 10 vor 10 or Tagesschau and the ZIB2 for example.

I guest, there must be free streams. If you will integrate them, I will help trying to search, if you want.

Thanks

Amadeus

**Comment by cemrich** [comment]
I've thought about that (see issues #1 and #2) and would like to support Swiss and Austrian channels. However, ORF at http://tvthek.orf.at/live/ does use flash video format which cannot be played back on Android and SRF is geoblocked in Germany, so I cannot debug it. But if you want and are able to help, please feel free to make a pull request or document your research in those two issues.
