### ISSUE TITLE
Make the channel list keyboard-friendly

### ISSUE THREAD

**Issue by rnauber** [cemrich/zapp#48]
The channel list currently can not be navigated with a keyboard/D-pad. This is especially bad for devices without a touchscreen/mouse (like TV sets).

Thank you,
Richard

**Comment by cemrich** [comment]
This issue will be resolved in v1.3.2. I will take some time until this version hits the fDroid repo. Please report any issues with this fix.

**Comment by rnauber** [comment]
That sounds great, I will soon test it...

**Comment by rnauber** [comment]
It works like a charm! Thank you for this great app!

**Comment by cemrich** [comment]
You're welcome :)
