### ISSUE TITLE
FR: display of broadcast metainformation

### ISSUE THREAD

**Issue by noerw** [cemrich/zapp#5]
I don't know if consistent APIs for this exist, but it would be great to have a display of the title and duration for the current selected show

**Comment by cemrich** [comment]
This would be a great feature and I'll look into it. Thank you!

**Comment by r10s** [comment]
Yes, that would be great.

However, I find the program already just now close to perfect :-) 
I seldom saw a program that was that easy to use and just works as expected.
Thank you _very_ much for your work up to now!

**Comment by rugk** [comment]
Yeah and if possible also show what is sent afterwards.

IMHO the current time should be shown in a progress bar, so you know how long the current TV program still takes. Well... that's just the way many TVs do it. :smiley:

**Comment by cemrich** [comment]
Basic functionality is released with version 1.0.0. Please create new tickets for any improvements or bugs.
