### ISSUE TITLE
Upnp-Support

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#52]

**Comment by rugk** [comment]
Hmm, why is this needed? I mean there should be no incoming connections…

**Comment by cemrich** [comment]
I would like to stream the tv channels to my media renderer (running with kodi) at home. I could use the share function and send the stream url to BubbleUPNP, however this does not work very reliably. 
I use cling to implement this function, but the library is hard to use without reading and understanding the complete upnp spec.

**Comment by cemrich** [comment]
The only available upnp library for android (cling) uses an untrusted repository and cannot be used for fdroid apps. Therefore I'll drop this enhancement.
