### ISSUE TITLE
Untrusted Cling lib blocks current versions in F-Droid

### ISSUE THREAD

**Issue by rojoweko** [cemrich/zapp#53]
According to https://gitlab.com/fdroid/fdroiddata/issues/805 current versions of Zapp cannot be included in F-Droid, because they consider the Cling lib used by Zapp untrusted (possibly not totally free). Is it possible to switch to one from a trusted maven repo or to resolve this differently?

Thanks for the great app! ;-)

**Comment by cemrich** [comment]
Thank you for your report. I already removed the offensive Cling library for version 1.4.2 but F-Droid updated may take a while.

**Comment by rojoweko** [comment]
Thanks a lot for taking care of this so quickly! I really appreciate this! ;-)

**Comment by cemrich** [comment]
Version 1.4.2 has now successfully build on F-Droid and will be available soon via website and app.
