### ISSUE TITLE
F-Droid does not show screenshots

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#54]
This is how the app looks here in F-Droid:
![zappfdrid](https://user-images.githubusercontent.com/11966684/28500087-251da39e-6fc3-11e7-8632-68779deef43b.png)

**Comment by rugk** [comment]
Or, wait, maybe the screenshots are hidden when the app is installed??

**Comment by cemrich** [comment]
No, that's an issue even if the app is uninstalled.

**Comment by cemrich** [comment]
Still not showing up. I asked for advise at https://forum.f-droid.org/t/screenshots-dont-show-up-in-client-using-gradle-play-publisher/881

**Comment by cemrich** [comment]
One F-Droid developer claimed [to have fixed this issue](https://gitlab.com/fdroid/fdroidserver/merge_requests/353). I'll wait for the fix to be published before closing this issue.

**Comment by cemrich** [comment]
Thanks to a F-Droid server fix it is working now!
