### ISSUE TITLE
Create draft for download feature

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#66]
I would like to let users download mediathek shows to watch them later. There are a few things to consider for this feature:

- Videos may be available in multiple sizes/resolutions
- The user may want to choose the download destination. A suitable default location is the public DIRECTORY_MOVIES or DIRECTORY_DOWNLOADS directory.
- Download progress can be tracked as notification and/or inside the shows detail view and/or inside the list view
- The show could be marked as downloaded when finished.
- There could be a filter for downloaded shows.

**Comment by rugk** [comment]
Nice idea, as for the default location I would suggest "DIRECTORY_MOVIES/zapp". As you said, maybe adjustable in the settings.

> Videos may be available in multiple sizes/resolutions

Just download the highest one… or let the user adjust it. (in the settings, not per download, IMHO)

> Download progress can be tracked as notification and/or inside the shows detail view and/or inside the list view

Notification. :+1:

**Comment by cemrich** [comment]
Okay, the android DownloadManager with notification was easy enough to use. Next release will contain an implementation where every quality settings can be downloaded into DIRECTORY_MOVIES/zapp. All additional features will be handled in separate issues.
