### ISSUE TITLE
Media center shows network error when scrolling down

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#67]
On two LineageOS devices I could reproduce this error: Scroll down in the media center (Mediathek) and the last item you see is ~3 hours ago. At the end of the list an orange bar at the top appears claiming you have a network/connection error, which is obviously a wrong statement.

v1.5.0-floss

This only happens **sometimes**. When trying to reproduce it right now, it strangely worked.

**Comment by erudisch** [comment]
Hello there

Inside the media center tab I just see the orange information bar claiming there is a connection error. No content anyway. I did an update today but still no change. I've got a s7 with recent Samsung ROM. 

Any ideas?
Regards Erik

**Comment by cemrich** [comment]
Okay, this seems to be a common issue and I'll look into it. I's not a Lineage error, because my test device is running Lineage.

Could you please provide information about your Android version?

**Comment by cemrich** [comment]
All right, I can reproduce this error on an Android 7.0 emulator:

    E/MediathekListFragment$S: javax.net.ssl.SSLHandshakeException: Handshake failed

**Comment by rugk** [comment]
I am also running LIneageOS 14.1 (based on Android 7).

So:
> I's not a Lineage error, because my test device is running Lineage.

This, is, AFAIK/IMHO, not a logical conclusion…

**Comment by erudisch** [comment]
I've got stock Samsung ROM (Android 7.0) with latest updates and also got this error. So I don't think it's a lineage error.

**Comment by rugk** [comment]
Hmm, at least both Android 7. Maybe there's the problem.

**Comment by cemrich** [comment]
This is a confirmed bug in Android 7.0 and can be fixed by falling back older cipher suites: https://stackoverflow.com/questions/39133437/sslhandshakeexception-handshake-failed-on-android-n-7-0

**Comment by cemrich** [comment]
This should be fixed with version 1.7.1 which should hit F-Droid the next few days. Alternatively you can use the [Github-Release](../releases/tag/v1.7.1). 

I hope the changes fixed the error for good. For devices which do support none of the added ciphers,  a more precise error message will show up.

**Comment by rugk** [comment]
The thing is I use Android 7.1.2 so the bug should be fixed there, already… Should… :thinking:

**Comment by cemrich** [comment]
Yes, if some videos are loading it has to be another bug / network issue. To find out the cause you can grep your logcat for "MediathekListFragment" as soon as the error occurs. There should be a full stack trace and a more specific error message.

I'll implement a way to report those non-crashing errors in the future so bugs can be fixed more easily.

**Comment by cemrich** [comment]
@rugk Do you still encounter this error?

**Comment by rugk** [comment]
no
