### ISSUE TITLE
WDR-Stream broken

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#72]
The WDR live stream is broken and does not load.

The new stream url can be extracted from the [ARD mediathek website](http://www.ardmediathek.de/tv/WDR-Fernsehen/live?kanal=5902) and updated in the [mediathek config file](https://github.com/cemrich/zapp/blob/master/app/src/main/res/raw/channels.json).

Please feel free to ask if you have any question on how to proceed!

**Comment by Medusalix** [comment]
I've extracted the new url, opened it with VLC and it seems to be working :+1:. If you don't mind I'll submit a PR tomorrow ready for the Hacktoberfest :smile:.

**Comment by cemrich** [comment]
Of course! Can you test it on an actual device?

**Comment by Medusalix** [comment]
Sure, let me get some screenshots.
