### ISSUE TITLE
Background playback

### ISSUE THREAD

**Issue by Wiredframe** [cemrich/zapp#74]
I would LOVE if the stream could be played in background while I respond to a mail or check the weather. 👍

**Comment by rugk** [comment]
* the audio stream, of course

for everything else there is https://github.com/cemrich/zapp/issues/60

Also implemented in [NewPipe](https://github.com/TeamNewPipe/NewPipe/), BTW.

**Comment by Wiredframe** [comment]
Of course :) Thanks for clarification. I use NewPipe too and would love to have this feature for Zapp too :)

**Comment by cemrich** [comment]
This is a nice feature! Also NewPipe implements this quite nicely. I'll label this for Hacktoberfest as I'll not be able to implement this for quite a while.

**Comment by rugk** [comment]
Also Firefox implements this, basically, in a way you can switch the app or shut off the screen and the music continues.

**Comment by cemrich** [comment]
This will be implemented for Mediathek shows in the next release. Streams will follow soon.

**Comment by Wiredframe** [comment]
Absolutely awesome, thanks so much for this feature!
