### ISSUE TITLE
New ZDFneo logo

### ISSUE THREAD

**Issue by cemrich** [cemrich/zapp#75]
ZDFneo has a new logo which should be updated in Zapp. Head to the [Wikipedia article](https://de.wikipedia.org/wiki/ZDFneo) to to get the SVG version of the logo. Convert it to Android XML format and replace the old logo. It may be a good idea to change ZDFneos [channel color](https://github.com/cemrich/zapp/blob/master/app/src/main/res/raw/channels.json).

**Comment by vipulasri** [comment]
I would like to work on this. @cemrich

**Comment by vipulasri** [comment]
@cemrich As far as I see, the above issue is already resolved in the latest code.

**Comment by bvdaakster** [comment]
Added the new logo and color in #77 
![screenshot_20171008-162108](https://user-images.githubusercontent.com/30904649/31317641-eaec62d2-ac44-11e7-9f4f-43b29302f908.png)

**Comment by cemrich** [comment]
Thank you @bvdaakster for your contribution!

@vipulasri I don't know what you mean.
