### ISSUE TITLE
Settings for loud speaker to use

### ISSUE THREAD

**Issue by rugk** [cemrich/zapp#8]
Settings for the loud speaker to use:
always "usual" one, front lout speaker, auto (chooses front loudspeaker when the proximity sensor is triggered)

**Comment by cemrich** [comment]
Can you provide an example of an app that implements this feature. I think this is more a system task than an app task.

**Comment by rugk** [comment]
I know no open-source app, but at least [Threema](https://threema.ch) implements it in their voice messages. For sending you need the "Voice Message Plugin" (download [here](https://shop.threema.ch/download) or [on Google Play](https://play.google.com/store/apps/details?id=ch.threema.voicemessageplugin)).
There the sound automatically switched from back to front loudspeaker when you move the phone to your ear when listening to a voice message.
I think WhatsApp does it in a similar way.

**Comment by cemrich** [comment]
Thank you.

I don't think this feature is worth the headache now or in near future, so I'll close the issue for now.
