### ISSUE TITLE
Kika changed its live stream, update address

### ISSUE THREAD

**Issue by rnauber** [cemrich/zapp#80]
![screenshot_20171022-155621](https://user-images.githubusercontent.com/7414650/31862680-2c6b1034-b742-11e7-9630-053cc3db716b.png)

Thank you...

**Comment by cemrich** [comment]
Thank you for your report! 

The new stream url seems to be `https://kikade-lh.akamaihd.net/i/livetvkika_de@450035/master.m3u8`.
The url can be updated at https://github.com/cemrich/zapp/blob/master/app/src/main/res/raw/channels.json

This is a nice issue for beginners in Android development 👍  Please claim the issue before you start working on it.

**Comment by SubhrajyotiSen** [comment]
I'm on it

**Comment by cemrich** [comment]
The next update will contain the fixed url.

**Comment by rnauber** [comment]
I can not wait :) ! Thank you!

**Comment by cemrich** [comment]
The updated version 1.8.1 will be released soon on F-Droid.
