### ISSUE TITLE
Stream artifacts

### ISSUE THREAD

**Issue by Lesik** [cemrich/zapp#87]
Not sure about exoplayer being "the better player", but few seconds in a stream I get visual artifacts, no matter what stream:
![screenshot_20171106-150123](https://user-images.githubusercontent.com/2021487/32663226-7c534f54-c62d-11e7-837e-2c16044b7cd2.png)

Other than that, I am really enjoying the application. My device, a Samsung Galaxy S4 mini, is running Android 7.1, and I got Zapp from F-Droid.

**Comment by cemrich** [comment]
Wow, that is very odd. I've never seen this error before so I have somehow narrow down the broblem.
- Have you tried restarting your device?
- Which device are you using? 
- Do you have similar or other problems if you share the stream url to another video player like vlc or google video?
- Do mediathek videos show the same artifacts?

Than k you very much for your help!

**Comment by ossapandra** [comment]
Hello, I too have this problem where the video is totally messed up with fragments/greenscreen. It is on this device:
Tablet, Alcatel One Touch Pixi 10, Android 5.1
Only Livestreams are affected, the Mediathek Videos play nice. I tried ARD and SWR.
Restarting the device does not change it.
But the official SWR-App does show the livestream without problems.
I hope someone can find and fix the bug.

Ciao!

**Comment by cemrich** [comment]
With 1.10.0 I updated exo player to the latest version. Please let me know if the problem persists.

**Comment by ossapandra** [comment]
It works now!

**Comment by cemrich** [comment]
Nice! Thank you very much for your feedback.
