### ISSUE TITLE
Feature Request: Stream only with wifi connection

### ISSUE THREAD

**Issue by deMattin** [cemrich/zapp#89]
If you stream with wifi connection and then lose the wifi connection without noticing, your 3G/LTE data plan is accidently and unwanted used.
It would be a good enhancement, if you could limit the streaming to wifi with an option like "Restrict streaming to wifi".

**Comment by cemrich** [comment]
Sounds good! I will try to implement this whenever I have some spare time :)

**Comment by cemrich** [comment]
I added the feature for version 1.10.0. The setting "stream over wifi only" will be enabled by default. Please let me know if you have any further suggestions or encounter bugs!

**Comment by rugk** [comment]
> The setting "stream over wifi only" will be enabled by default. 

Hu? Don't know whether many users expect this. You may warn that such a stream uses much mobile data, but in the end if I open Zapp when I'm in a mobile network, of course I still want to watch the stream.

**Comment by cemrich** [comment]
Well, you can uncheck the setting as described in the error message.

**Comment by deMattin** [comment]
Thanks for the enhancement.
I think, it is the right choice to set defaults to not stream over mobile data plan.
All apps with possible high data usage behave like that.
