### ISSUE TITLE
Feature Request: Control volume by wiping

### ISSUE THREAD

**Issue by Buntbart** [cemrich/zapp#90]
I would like to be able to adjust the brightness and volume with vertical wiping gestures in the left and right half of the screen. This is possible in VLC and NewPipe.

**Comment by cemrich** [comment]
Thank you very much for this suggestion. I won't prioritize this very high but I'll keep it in the backlog.

**Comment by cemrich** [comment]
Relevant section in NewPipe: https://github.com/TeamNewPipe/NewPipe/blob/fd5cbde18cf4614af6ceaa76d1095ecabd369a20/app/src/main/java/org/schabi/newpipe/player/MainVideoPlayer.java

**Comment by cemrich** [comment]
This feature is now implemented in Zapp 1.11.0.

**Comment by Buntbart** [comment]
Thank You! :-)
