### ISSUE TITLE
Loading animation is shown while video plays

### ISSUE THREAD

**Issue by lightonflux** [cemrich/zapp#93]
Sometimes with slower internet connections the loading animation is shown above the playing video, which is very annoying.

The loading animation should only be visible if the video is stopped because if a
N empty buffer. But not when the video is playing without problems or stutter.

**Comment by cemrich** [comment]
Are you talking about the live streams, the mediathek videos or both?

**Comment by obert99** [comment]
I do support this issue. The small animated load bar on the buttom of the screen (live stream), distracts. If some people might need it, maybe the visibility can be made optional in the config.
Anyway, thanks a lot for the tool!

**Comment by cemrich** [comment]
With the next release the loading animation should only show up when the buffer is completely empty. Please report back if this issue should reappear.
