### ISSUE TITLE
ssl error message again

### ISSUE THREAD

**Issue by axel-rank** [cemrich/zapp#95]
using lineage 7.1.2
live streams work
mediathek does not
message: your device is unable to establish an encrypted connection to server, it might help to update your android version.
strange thing, because mediathek has worked after first install, but suddenly it stopped???

**Comment by cemrich** [comment]
It was a SSL error caused by server changes. The error should be fixed in the upcoming 1.9.1 release. As always it will take a while before the release hits F-Droid.

**Comment by guest4711** [comment]
1.9.1 works for me. Thanks.

**Comment by odoooooo** [comment]
Where die you find 1.9.1?
In F-Droid I only can see 1.9.0

**Comment by cemrich** [comment]
F-droid need a few days to a week to detect and build new releases and I can't speed up this process. If you don't want to wait for the F-Droid release you can find the release here: https://github.com/cemrich/zapp/releases/tag/v1.9.1 You have to uninstall any existing F-Droid version from your device in order to install it.

**Comment by guest4711** [comment]
Directly from github. Because f-droid uses it own key for signing it's not possible to update it directly. So you have to uninstall the f-droid version first. So your settings for zapp are lost and you have to rearrange the station list again if you ever touched it...

**Comment by axel-rank** [comment]
any sha1/2 sums available for integrity check of download version?

**Comment by cemrich** [comment]
@axel-rank Nope, I did not create check sums.

**Comment by jcgruenhage** [comment]
F-Droid had problems building the new version originally, which is why it took a little longer, but the build succeeded yesterday in the evening and it should be pushed to the repos in the next few days.

**Comment by guest4711** [comment]
Thanx for the info....

**Comment by jcgruenhage** [comment]
Is out now, so this can be closed ^^

**Comment by axel-rank** [comment]
ok

**Comment by cemrich** [comment]
Thank you all for your support!

**Comment by jcgruenhage** [comment]
Thank you for the amazing app ;)
