### ISSUE TITLE
Please add free private Channels

### ISSUE THREAD

**Issue by bjoernkoenig** [cemrich/zapp#99]
There are lots of private german and international Channels, which are accessible for free online from the Channels homepages or the channels youtube pages - without geoblocking, for example the german News Channel N24, Euronews (Germany), MTV, France24, Sky TG24 Italia, RAINews24, BBC World News, Franceinfo and others. Please add these Channels.

**Comment by cemrich** [comment]
Sorry, but I won't do that. The legal situation is wonky enough without adding private channels.
